service: auth-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 29 # optional, icrease from default (6), cold start

  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    #test Arm architecture per function maybe switch to global 34% better price/perfomance
    architecture: arm64

    events:
      - http:
          path: api/get-auth-url
          method: get

  getAccessToken:
    handler: handler.getAccessToken
    architecture: arm64

    events:
      - http:
          path: api/token/{code}
          method: get

  getCalandarEvents:
    handler: handler.getCalendarEvents
    architecture: arm64

    events:
      - http:
          path: api/get-events/{access_token}
          method: get
